site_name: My Docs

theme:
  name: "material"


nav:
  - Home: index.md
  - Spatiotemporal Wildlife Classification: https://trav-d13.github.io/spatiotemporal_wildlife_classification/
  - DSN Central: https://spatiotemporal-wildlife-classification.github.io/Distributed-Scraping-Network/
  - DSN Leaf: https://spatiotemporal-wildlife-classification.github.io/DSN-Leaf/